trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  projectName: 'VersionEndpoint'

steps:
- task: DotNetCoreCLI@2
  displayName: 'restore'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'build'
  inputs:
    command: 'build'
    projects: '**/VersionEndPoint.Middleware.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: test
    projects: '**/tests/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: DotNetCoreCLI@2
  displayName: 'pack'
  inputs:
    command: pack
    projects: '**/VersionEndPoint.Middleware.csproj'
    packDirectory: $(Build.ArtifactStagingDirectory)/$(projectName)
    versioningScheme: off

- task: NuGetAuthenticate@0
  displayName: 'NuGet Authenticate'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/$(projectName)/*.nupkg;!$(Build.ArtifactStagingDirectory)/$(projectName)/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '89168acf-a74f-48ae-acbb-004b81944d9d'